# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mlrpg',
                'doc_host': 'https://alexrodpas.github.io',
                'git_url': 'https://github.com/alexrodpas/mlrpg',
                'lib_path': 'mlrpg'},
  'syms': {'mlrpg.core': {'mlrpg.core.foo': ('core.html#foo', 'mlrpg/core.py')}}}
