project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4
    grid:
      body-width: 1100px

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/alexrodpas/mlrpg"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]